# keep in sync with what we have in docker-compose, though with different ips/ports. This is for use in gitpod
akhq:
  server:
    access-log:
      enabled: true
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]" # Logger format
  connections:
    docker-kafka-server:
      properties:
        bootstrap.servers: "172.20.10.12:9092"
      schema-registry:
        url: "http://172.20.10.14:8081"
      connect:
        - name: kafka-connect-1
          url: "http://172.20.10.18:8084"
