image:
  file: .gitpod.dockerfile

tasks:
  # currently only using command, but might try out init or prebuild later
  # First, install external java packages. Runs only once per gitpod build
  - init: mvn -f ./connect-api-with-kafka-consumers/kafka-to-cassandra-worker/pom.xml clean package

  # Then, start Kafka using confluent community platform
  # https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#start-cp
  - command: sudo systemctl start confluent-zookeeper
  - command: sudo systemctl start confluent-kafka
  - command: sudo systemctl start confluent-schema-registry
  # might need to do one of these
  # - command: chown cp-schema-registry:confluent /var/log/confluent && chmod u+wx,g+wx,o= /var/log/confluent
  # - command: chown cp-kafka-rest:confluent /var/log/confluent && chmod u+wx,g+wx,o= /var/log/confluent
  # - command: chown cp-ksql:confluent /var/log/confluent && chmod u+wx,g+wx,o= /var/log/confluent
  - command: sudo systemctl start confluent-kafka-rest
  - command: sudo systemctl start confluent-kafka-connect
	- command: java -Dmicronaut.config.files=./connect-api-with-kafka-consumers/kafka/akhq/akhq-config.yml -jar akhq.jar

  # these ones, user can start themselves when they want to use something in particular
  # - command: sudo systemctl start confluent-kafka-rest


