image:
  file: .gitpod.dockerfile

tasks:
  # First, install external java packages. Runs only once per gitpod build
  # NOTE starts at $PROJECT_HOME, i.e., /workspace/cassandra.realtime
  - init: mvn -f ./kafka-to-cassandra-worker/pom.xml clean package

  # Then, start Kafka using confluent community platform

  # Trying doing everything using confluent CLI once
  - command: confluent local start
  
# expose ports we want open
ports:
  - port: 8080

