---
version: '2'

networks:
  kafka_dse_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.10.0/24
          gateway: 172.20.10.1

services:
  ###
  ### DSE
  ###
  dse:
###    image: datastax/dse-server:6.8.0 # SPARK 2.4
    image: datastax/dse-server:6.7.7  # SPARK-2.2
    container_name: dse_007
    command: [-k]
    environment:
      DS_LICENSE: accept
      JVM_EXTRA_OPTS: -Xms2g -Xmx2g
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    ports:
      - "4040:4040"
      - "7080:7080" # SPARK MASTER
      - "7081:7081" # SPARK WORKER
      - "8983:8983"
      - "9042:9042"
      - "9077:9077"
      - "10000:10000"
    networks:
      kafka_dse_network:
        ipv4_address: 172.20.10.09

  ###
  ### PYTHON FLASK, EXCEL FILE
  ###
  python:
    build: ./python
    image: python-flask-app-for-kafka:latest
    container_name: python_app
    ports:
      - "5000:5000"
    networks:
      kafka_dse_network:
        ipv4_address: 172.20.10.10

  ###
  ### KAFKA ZOOKEEPER
  ###
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: kafka_zk
    ports:
      - "22181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafka_dse_network:
        ipv4_address: 172.20.10.11

  ###
  ### KAFKA WORKER
  ###
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: cp_kafka_007
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 172.20.10.11:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.20.10.12:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      kafka_dse_network:
        ipv4_address: 172.20.10.12

  ###
  ### KAFKA MANAGER
  ###
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka_manager
    depends_on:
      - zookeeper
    environment:
      ZK_HOSTS: 172.20.10.11:2181
    ports:
      - "29000:9000"
    networks:
      kafka_dse_network:
        ipv4_address: 172.20.10.13
